##  http://localhost:8090/h2-console
server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:./ijuju_dev;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      uri: mongodb://localhost:27017/ijuju
  redis:
    host: localhost
    port: 6379
